### PR TITLE
chore(web-server): update to Rust SGX SDK 1.1.4

### PR DESCRIPTION
**Pull request by PiDelport**
Upstream:

- https://github.com/apache/incubator-teaclave-sgx-sdk/issues/360
- https://github.com/apache/incubator-teaclave-sgx-sdk/pull/363

This updates our dependency to upstream revision: [e8a9fc22](https://github.com/apache/incubator-teaclave-sgx-sdk/commit/e8a9fc22939befa27ff67f5509b2c2dfe8499945)

### CODE REVIEW

**Comment by PiDelport** [comment]
I bumped the Rust SGX SDK revision one more time, before merging.

Everything else should still be up to date, and ready to merge.

**Review by IscoRuta98 — COMMENTED** [review]
Hi @PiDelport, 
I was able to make the updates locally, and run the sgx-wallet-test with no issues (see below). No further comments at this time.

image

**Review by billguo99 — APPROVED** [review]
LGTM!

**Comment by PiDelport** [comment]
Awesome, thanks! 😊

**Pull request merged**
