### PR TITLE
fix(web-client): check wallet id on scan success

### PR DESCRIPTION
**Pull request by jongbonga**

### CODE REVIEW

**Comment by billguo99** [comment]
rebase with main :)

**Comment by billguo99** [comment]
Where do you access the scan page to scan a QR code? I clicked "open wallet" but it doesn't give option to scan QR code.

**Comment by jongbonga** [comment]
This PR addresses something else. If you are running the code locally, you can remove `hasCamera` on the wallet access template to test

**Comment by billguo99** [comment]
> This PR addresses something else. If you are running the code locally, you can remove `hasCamera` on the wallet access template to test

What does this PR address?
Is this only for mobile app?
Which file should I remove `hasCamera`?

**Comment by billguo99** [comment]
I removed `hasCamera` ng-container block and Access wallet with QR code option worked. I don't have a wallet address QR code to test so that's as far as I've tested. The option comes up and the camera webcam works.

**Review by billguo99 — APPROVED** [review]

**Review by IscoRuta98 — APPROVED** [review]

**Pull request merged**
